trigger:
- master

pool:
  name: tzl-poc
  demands:
    - agent.name -equals tzl-poc-ado-f69787499-5cc9b

steps:
- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'sonar-furkan-deneme'  # Adım 1'de oluşturduğunuz Service Connection ismini kullanın
    scannerMode: 'CLI'
    configMode: 'manual'
#    cliProjectKey: 'your_project_key'
    cliSources: '.'

- script: echo 'Kod taraması başlatılıyor...'
  displayName: 'Echo'

- task: SonarQubeAnalyze@4

- task: SonarQubePublish@4
  inputs:
    pollingTimeoutSec: '300'