trigger:
- master

pool:
  name: tzl-poc
  demands:
    - agent.name -equals tzl-poc-ado-f69787499-5cc9b

steps:
- checkout: self
- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'sonar-furkan-deneme'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'sonar-furkan-deneme'
    cliSources: '.'

- task: SonarQubeAnalyze@5
  inputs:
    jdkversion: 'JAVA_HOME_11_X64'

- task: SonarQubeAnalyze@5
  inputs:
    jdkversion: 'JAVA_HOME'


- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'

- script: echo 'Kod taraması başlatılıyor...'
  displayName: 'Echo'

- task: SonarQubeAnalyze@4



